format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\
$c\
$golang\
$ruby\
$lua\
$python\
$rust\
$zig\
$haskell\
$ocaml\
$vlang\
$nodejs\
$deno\
$php\
$cmake\
$buf\
\
$docker_context\
$kubernetes\
$helm\
$terraform\
$vagrant\
$aws\
$gcloud\
$openstack\
$azure\
\
$package\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

palette = "gruvbox"

[palettes.sigma]
black = "#161616"
white = "#F6FADE"
green = "#5AD1AA"
red = "#F92672"
purple = "#9C75F0"
blue = "#51A3D6"
yellow = "#FFD700"
cyan = "#00BFA4"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.gruvbox]
black = "#1D2021"
white = "#D4BE98"
red = "#EA6962"
green = "#A9B665"
yellow = "#D8A657"
blue = "#7DAEA3"
magenta = "#D3869B"
cyan = "#89B482"


# [hostname]
# ssh_symbol = " "

# sigma theme settings
# # ➜    󰁕      󱦰 
# [character]
# success_symbol = "[](bold cyan)"
# error_symbol = "[](bold red)"
#
# [directory]
# style = "bold blue"
# # read_only = " 󰌾"
# end sigma theme settings

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
# style = "bold lavender"
style = "bold blue"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold red"
symbol = " "
# symbol = " "

[ruby]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[golang]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "
style = "bold blue"

# [c]
# symbol = " "

[lua]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[python]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[rust]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[haskell]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[package]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = "󰏗 "

[nodejs]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
symbol = " "
detect_extensions = []
# disabled = true

[docker_context]
format = "[$symbol]($style)"
# symbol = "󰡨 "

# [aws]
# symbol = "  "

[memory_usage]
symbol = "󰍛 "

[jobs]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
