format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\
$c\
$golang\
$ruby\
$lua\
$python\
$rust\
$swift\
$zig\
$haskell\
$ocaml\
$vlang\
$nodejs\
$deno\
$php\
$cmake\
$buf\
\
$docker_context\
$kubernetes\
$helm\
$terraform\
$vagrant\
$aws\
$gcloud\
$openstack\
$azure\
\
$package\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

palette = "sigma"

[palettes.sigma]
black = "#161616"
white = "#F6FADE"
green = "#5AD1AA"
red = "#F92672"
purple = "#9C75F0"
blue = "#51A3D6"
yellow = "#FFD700"
cyan = "#00BFA4"

# [hostname]
# ssh_symbol = " "

# ➜    󰁕      󱦰 
[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"

[directory]
style = "bold blue"
# read_only = " 󰌾"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold red"
symbol = " "
# symbol = " "

[ruby]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[golang]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "
style = "bold blue"

# [c]
# symbol = " "

[lua]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[python]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[rust]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[haskell]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = " "

[package]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
# symbol = "󰏗 "

[nodejs]
format = "[$symbol]($style)[$version ](bold yellow)"
version_format = "${raw}"
symbol = " "
detect_extensions = []
# disabled = true

[docker_context]
format = "[$symbol]($style)"
# symbol = "󰡨 "

# [aws]
# symbol = "  "

[memory_usage]
symbol = "󰍛 "

[jobs]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
